---
Name: cookie-policy-notification
---
PageController:
  extensions:
    - Fractas\CookiePolicy\CookiePolicy
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Fractas\CookiePolicy\CookiePolicySiteConfig
---
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    fetchcookiepolicy: Fractas\CookiePolicy\CookiePolicyController
